### ISSUE TITLE
Update Payment status

### ISSUE THREAD

**Issue by sridhargoshika** [AcuityScheduling/acuity-php#5]
How to update the payment status once the new appointment is created?
The following endpoint is used to create a new appointment, I want to update the payment status after the appointment is created.
POST: `https://acuityscheduling.com/api/v1/appointments`
The following endpoint is used to retrieve the list of payment transactions,
GET: `https://acuityscheduling.com/api/v1/appointments/id/payments`

**Comment by cesutherland** [comment]
Hello Sridhar! We do not have a public endpoint today for recording or updating payments through our API, or plans to add one at this time, unfortunately.
